### ISSUE TITLE
go.mod: verifying module: checksum mismatch

### ISSUE THREAD

**Issue by qcasey** [jnovack/mosquitto-exporter#1]
Looking to try your fork out and got:

go: github.com/jnovack/go-version@v1.0.0/go.mod: verifying module: checksum mismatch
	downloaded: h1:s8DZ+9C9fQ7sK2KO8KDvuAIJgX+nzHGfXxgZyV/aGrY=
	sum.golang.org: h1:+wCtyeQ6/Ttm8Ih/g+48icj4NyFTvKqCC3v61ZV1CLs=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
ERROR: Service 'gobybox_mqtt' failed to build: The command '/bin/sh -c go mod download' returned a non-zero code: 1

**Comment by qcasey** [comment]
That being said after changing the checksums manually for both the repo and go.mod it works great. Nice job :)

**Comment by jnovack** [comment]
Ugggggh. I know.  That library is a cancer that I just had to rewrite because of how Go does their versioning.  I should fix it. Thank you.
